Module7 task1
htmlacademy-react/838151-six-cities-9 pull request #10
Opened 2022-03-18 12:02 UTC by Kiriuha-lucky

2022-03-25 02:42 UTC, yurylavrukhin requested changes
отличная сортировка 😍

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +  const currentOffers = offers.filter((offer) => offer.city.name === currentCity).sort(sortOffers());
и мне кажется что название для переменной в который лежит **тип сортировки офферов** стоит поменять на `offersSortType` или `offersSortingType`

сейчас она называется `offersSort` — **офферы сортировка**, по такому названию можно неправильно понять что там лежит

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +  const offersSort: string = useAppSelector((state) => state.offersSort);
сотри пожалуйста указание типов для возвращаемых значений от useAppSelector, эта функция типизирована и TS сам укажет тип возвращаемого значения

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +/* eslint-disable*/
cотрите нас по всему проекту пожалуйста

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +    transform: 'rotate(180deg)',
перенесите пожалуйста стили в CSS-файл, и управляйте ими через className
https://reactjs.org/docs/faq-styling.html

там можно будет и `transition` добавть чтобы была плавная анимация

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +    transform: 'rotate(180deg)',
стрелка прыгает в состоянии `open`, я вижу проблему

https://user-images.githubusercontent.com/26966797/160042890-a98d8973-bec7-4814-b694-772d1c5cd6b7.mov

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +    <form className="places__sorting" action="#" method="get" onClick={() => setOpen(!open)}>
везде где чувак может кликать — нужен `cursor: pointer;`

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +    transform: 'rotate(180deg)',
**СМОТРИ ТОЛЬКО ЕСЛИ НЕ НАШЁЛ ПРОБЛЕМУ САМ**
_[подсказка](https://stackoverflow.com/questions/10765755/how-to-apply-multiple-transforms-in-css)_
**СМОТРИ ТОЛЬКО ЕСЛИ НЕ НАШЁЛ ПРОБЛЕМУ САМ**

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/types/api.types.ts
> +export const APIRoute = {
**это можно игнорировать**
где-то ты используешь enum, где-то const 
в этом проекте это не супер-важно

в реальном проекте придерживайся одной стратегии, с командой договорённость сделайте

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/store/reducer.ts
> +  offersSort: string,
`offersSortingType`

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/types/sort-type.ts
> +export const SORT_TYPES: string[] = [
нужен тип правильный `OffersSortingType[]`

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +        {SORT_TYPES.map((sortType) => <li key={sortType} className={`places__option ${sortType === offersSortActive ? 'places__option--active' : ''}`} tabIndex={0} onClick={() => { dispatch(offersSor
вынеси обработчик клика в тело компонента

2022-03-25 02:42 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +    <form className="places__sorting" action="#" method="get" onClick={() => setOpen(!open)}>
вынеси обработчик клика в тело компонента

2022-03-25 09:11 UTC, Kiriuha-lucky commented on project/src/components/offers-sort/offers-sort.tsx
> +    transform: 'rotate(180deg)',
я добавил поворот, подсказку не смотрел, но и у меня стрелка так не прыгает, а просто крутиться на месте, если все также прыгает я еще подумаю

2022-03-25 09:25 UTC, Kiriuha-lucky commented on project/src/components/offers-sort/offers-sort.tsx
> +    <form className="places__sorting" action="#" method="get" onClick={() => setOpen(!open)}>
а на каком элементе нет курсора? у меня и на открытии списка и на каждом элементе списка он есть.

2022-03-25 09:52 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.tsx
> +    <form className="places__sorting" action="#" method="get" onClick={() => setOpen(!open)}>
при клике на текст **sort by**

посмотри 8ми секундное видео в соседнем комментарии

2022-03-25 10:27 UTC, yurylavrukhin requested changes

2022-03-25 10:27 UTC, yurylavrukhin commented on project/src/components/offers-sort/offers-sort.css
> +  transform: rotate(0);
теперь стрелка вертикально не по центру с текстом

2022-03-25 10:27 UTC, yurylavrukhin commented on project/src/store/action.ts
> +);
типов нет для пейлоада :( 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/26966797/160101443-e5434caa-02ee-400b-8d4e-ecdafa5c1345.png">

2022-03-25 10:27 UTC, yurylavrukhin commented on project/src/types/sort-type.ts
> +export const SORT_TYPES: string[] = [
добавь тип здесь — литерал строк

2022-03-25 10:27 UTC, yurylavrukhin commented on project/src/store/reducer.ts
> +  offersSortingType: 'Popular' | 'Price: low to high' | 'Price: high to low' | 'Top rated first',
используй здесь тип `OffersSortTypeTypes`, сейчас он дублируется здесь

2022-03-26 03:35 UTC, yurylavrukhin requested changes
поправь эти ошибки, пожалуйста
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/26966797/160222547-5c86a97f-952b-425e-86db-5a15ecc0ece7.png">

проверяй свой код перед отправкой на ревью, это ускорит нашу работу, если ты сам будешь находить ошибки и их исправлять до того как их увижу я

ещё 3 момента попросил сделать в видео 🙏

2022-03-26 12:57 UTC, merged