Module7 task2
htmlacademy-react/838151-six-cities-9 pull request #11
Opened 2022-03-26 14:46 UTC by Kiriuha-lucky

2022-03-31 17:31 UTC, yurylavrukhin requested changes
настоящее приложение получается, круто!

вопрос есть:
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/26966797/161112982-89e4536b-8759-407b-abfb-921b872d0fff.png">
юзер зашёл на сайт незалогиненный и сразу получает ошибку, это ок?

2022-03-31 17:31 UTC, yurylavrukhin commented on project/src/components/review-form/review-form.tsx
> +      onSubmit({ ratingCount: rating, comment: reviewText, id: Number(offerId) });
ты переименовываешь rating в ratingCount, а потом в thunk-е снова в rating
нужно убрать это бессмысленное переименование

2022-03-31 17:31 UTC, yurylavrukhin commented on project/src/components/login/login.tsx
> +                <input className="login__input form__input" ref={loginRef} type="email" name="email" placeholder="Email" required />
о, интересно!
я обычно использую local state + handler для получения значения инпута, а тут реф

как ты узнал об этом способе?
в чём преимущества? минусы? подводные камни?

2022-03-31 17:31 UTC, yurylavrukhin commented on project/src/services/token.ts
> +const AUTH_TOKEN_KEY_NAME = 'six-sities';
```suggestion
const AUTH_TOKEN = 'six-sities';
```

2022-03-31 17:31 UTC, yurylavrukhin commented on project/src/store/api-actions.ts
> +      return api.get<Offer>(`${APIRoute.Offer}/${id}`);
**этот комментарий можно игнорировать**

1. у нас сейчас данные дублируются в сторе в поле offers и здесь одинаковый оффер
2. при заходе на один и тот же оффер в рамках спа, он будет повторно фетчится

как простая рабочая реализация это ок

было бы круче если бы мы находили оффер в state.offers и не фетчили, а если оффер не найден в этом списке — только тогда фетчили, например когда мы напрямую заходим на страницу оффера, а не переходим с главной

можно ещё заморочиться с сохранением reviews и соседних офферов в стор, но это микрооптимизации в рамках этого проекта не стоит этим заниматься

2022-03-31 17:31 UTC, yurylavrukhin commented on project/src/components/header/header.tsx
> +          {authorizationStatus !== AuthorizationStatus.Auth ? (
можно вынести в переменную isAuthorized и сложить в тело компонента

2022-03-31 17:31 UTC, yurylavrukhin commented on project/src/components/app/app.tsx
> +  const {offers, authorizationStatus } = useAppSelector((state) => state);
перенеси селектор офферов в favorites
а селектор authorizationStatus в privateroute

2022-04-01 07:48 UTC, Kiriuha-lucky commented on project/src/components/login/login.tsx
> +                <input className="login__input form__input" ref={loginRef} type="email" name="email" placeholder="Email" required />
В демонстрации увидел,  просто метод с local state + handler я использовал в добавлении комментария в форме, а здесь достаточно просто достать данные как я думаю.

2022-04-02 08:38 UTC, yurylavrukhin requested changes
спасибо за такую быструю работу! я постараюсь придерживаться твоего ритма

поправь зависимости useEffect'a, у нас с ним появились проблемы

2022-04-02 08:38 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
>    const cities = useAppSelector((state) => state.cities);
давай перенесём этот селектор в `<CitiesList/>`, он же не используется в main

2022-04-02 08:38 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +  }, [isDataLoaded]);
лишняя зависимость
```suggestion
  }, [fetchData]);
```
запрашиваем 2 раза данные - это плохо

2022-04-02 08:38 UTC, yurylavrukhin commented on project/src/components/property/property.tsx
> +  }, [offerId, isDataLoaded]);
нужно убрать isDataLoaded, рассказал в видео

2022-04-03 05:23 UTC, yurylavrukhin commented on project/src/components/review-form/review-form.tsx
> +/*eslint-disable*/
🔪

2022-04-03 05:25 UTC, yurylavrukhin commented on project/src/components/review-form/review-form.tsx
> +      async (evt: FormEvent<HTMLFormElement>) => {
ну не прямо в разметке, вынеси асинхронную функцию обработчик в тело компонента

2022-04-03 09:21 UTC, yurylavrukhin commented on project/src/components/review-form/review-form.tsx
> +  const handleSubmit = async (evt: FormEvent<HTMLFormElement>) => {
👍

2022-04-03 09:21 UTC, merged