Module8 task2
htmlacademy-react/838151-six-cities-9 pull request #13
Opened 2022-04-06 20:23 UTC by Kiriuha-lucky

2022-04-07 12:45 UTC, yurylavrukhin requested changes

2022-04-07 12:45 UTC, yurylavrukhin commented on project/src/components/bookmark/bookmark.tsx
> +    return isFavorite ? dispatch(toogleFavorites({ id: id, isFavorite: 0, loc: loc })) : dispatch(toogleFavorites({ id: id, isFavorite: 1, loc: loc }));
сложно, мы можем упростить это выражение

2022-04-07 12:45 UTC, yurylavrukhin commented on project/src/store/api-actions.ts
> +        case (loc.includes('favorites')):
use APIRoute enum here

2022-04-07 12:45 UTC, yurylavrukhin commented on project/src/store/index.ts
> +  control: number,
control – очень абстрактное название, можем придумать более специфичное?

2022-04-07 12:45 UTC, yurylavrukhin commented on project/src/components/login/login.tsx
> +  function showCityOffers(city: string) {
ой как круто!

2022-04-07 12:48 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +      <Link to='/favorites'>Favorites</Link>
тогда мы сможем заходить прямо на /favorites если у нас есть токен, а сейчас нас выкидывает на главную, даже если мы залогинены

2022-04-07 13:27 UTC, Kiriuha-lucky commented on project/src/components/favorite-place-card/favorite-place-card.tsx
> +), (prevProps, nextProps) => prevProps.isFavorite === nextProps.isFavorite);
если не переопределить, то после удаления предложения все оставшиеся карточки перерисовываются, а так нет

2022-04-07 13:54 UTC, yurylavrukhin commented on project/src/components/favorite-place-card/favorite-place-card.tsx
> +), (prevProps, nextProps) => prevProps.isFavorite === nextProps.isFavorite);
эти перерисовки должны пропасть после внедрения нормализованного стора, потому что данные для соседних офферов изменяться не будут

2022-04-07 14:01 UTC, yurylavrukhin commented on project/src/components/favorite-place-card/favorite-place-card.tsx
> +), (prevProps, nextProps) => prevProps.isFavorite === nextProps.isFavorite);
сейчас если мы захотим изменить цену у оффера, например сделаем фичу с риалтайм ценой — компонент не перерисуется, это неожиданное поведение

конкретно в этом кейсе лучше поправить данные и оставить дефолтную мемоизацию

в целом — лучше мемоизацию оставлять дефолтной, править стоит её только в узких критичных для перформанса приложения моментах

это очень круто что ты нашёл эту проблему и решил её так! 💪

2022-04-08 06:33 UTC, yurylavrukhin requested changes

2022-04-08 09:41 UTC, Kiriuha-lucky commented on project/src/store/api-actions.ts
> +      return api.get<Offer>(`${APIRoute.Offers}/${id}`);
ну в начале я хотел чтобы роут для страницы и для запроса данных для страницы был одинаковый, но она не совпадают поэтому их пришлось подправить и из-за этого здесь тоже немного поменялось

2022-04-08 12:04 UTC, yurylavrukhin requested changes
супер!

2022-04-08 12:44 UTC, merged