Module2 task1
htmlacademy-react/838151-six-cities-9 pull request #4
Opened 2022-02-15 07:10 UTC by Kiriuha-lucky

2022-02-15 13:47 UTC, yurylavrukhin requested changes
спасибо за ПР! 

отличное начало 💪 

накинул несколько комментариев, не должно занять много времени поправить

уверен ты справишься сам
но если что я доступен в тележке, пиши!

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/room-card/room-card.tsx
> +function RoomCard(): JSX.Element {
кажется, название `RoomCard` не точно передаёт то, что находится в компоненте. там может быть не только room, но и apartment.

предлагаю переименовать компонент в `<PlaceCard/>` (смотри на названия классов в разметке — там это тоже place card)

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +                <RoomCard />
я вижу в разметке, что карточки отличаются

ценой, типом (Apartment, Private Room), названием, типом, может чем-то ещё, взгляни, пожалуйста, на карточки и сделай список того, что может отличаться в карточках

из полученного списка сделай интерфейс для компонента `<PlaceCard/>` и пробрось туда эти параметры как props

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +                <RoomCard />
получатся разные карточки, как в разметке 🎉

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/room-card/room-card.tsx
> +export default RoomCard;
старайся использовать везде named export - `export function MyComponent (){}`

тогда ты никогда не опечатаешься при использовании этого компонента в другом файле

потому что ты будешь импортировать `import { MyComponent } from '...'`
а дефолтный экспорт `export default MyComponent` позволяет тебе задавать имя компоненту

а мы всегда хотим назвать его так, как он называется при объявлении, так что дефолтный экспорт может только усложнить жизнь и создать опечатки

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/room/room.tsx
> +export default Room;
default export → named export

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/sign-in/sign-in.tsx
> +export default SignIn;
и здесь default export → named export

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/index.tsx
> +const OFFER_COUNT = 100;
прекрасно! 😍

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/index.tsx
> +const OFFER_COUNT = 100;
только `OFFERS_COUNT`, потому что их может быть > 1

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/app/app.tsx
>  export default App;
замени тут тоже, пожалуйста, default export → named export

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/favorites/favorites.tsx
> +export default Favorites;
default export → named export

2022-02-15 13:47 UTC, yurylavrukhin commented on project/src/components/room/room.tsx
> +function Room(): JSX.Element {
может назовём компоненты так как они называются в разметке?

1. Room → Property
2. SignIn → Login (p.s. Login, а не LogIn, потому что это не глагол, не действие, не название функции, а компонент — существительное https://twitter.com/andrew__romanov/status/1250703483445161988) 
3. а с Favorites всё прекрасно ❤️ 

мне кажется это the way to go

если называть одну сущность по-разному — можно запутаться, и запутать людей с которыми ты работаешь
в том числе и при коммуникации, не только в коде

2022-02-15 18:15 UTC, yurylavrukhin requested changes
топ! давай дополируем немного

2022-02-15 18:16 UTC, yurylavrukhin commented on project/src/index.tsx
> +const OFFERS = [
для этой константы добавим тип Offer[]

2022-02-15 18:21 UTC, yurylavrukhin commented on project/src/components/main/main.tsx
> +                {offers.map((offer) => <PlaceCard key={offer.id} offer={offer}/>)}
это лучше чем ожидалось! давай обернём это в семантические теги

div заменим на ul,
и обернём <PlaceCard/> в <li>

PlaceCard не должен знать ничего про то что он рендерится в списке, поэтому мы пробросим key в <li>

2022-02-15 20:22 UTC, Kiriuha-lucky commented on project/src/components/place-card/place-card.tsx
> +interface PlaceCardProps {
по критерию Б21 вроде же так правильно как сейчас

2022-02-15 20:29 UTC, Kiriuha-lucky commented on project/src/components/main/main.tsx
> +                {offers.map((offer) => <PlaceCard key={offer.id} offer={offer}/>)}
здесь почему то чего то не хватает и я не могу понять чего

2022-02-16 06:20 UTC, yurylavrukhin commented on project/src/components/place-card/place-card.tsx
> +interface PlaceCardProps {
отлично, оставляем как сейчас

2022-02-16 06:21 UTC, yurylavrukhin commented on project/src/components/place-card/place-card.tsx
> +interface PlaceCardProps {
я не знал про этот критерий,
теперь знаю благодаря тебе, спасибо

2022-02-16 07:59 UTC, merged