Module4 task1
htmlacademy-react/838151-six-cities-9 pull request #6
Opened 2022-02-24 11:16 UTC by Kiriuha-lucky

2022-02-27 12:28 UTC, yurylavrukhin requested changes
очень интерактивно получается 🥳

2022-02-27 12:28 UTC, yurylavrukhin commented on project/src/components/offers-list/offers-list.tsx
> +    <ul className="cities__places-list places__list tabs__content">
я тебя попросил добавить семантические теги, и теперь у нас в интерфейсе из-за этого маркеры рядом с элементами списка :(
сорри

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26966797/155881500-389a8e24-cbc4-4968-b4c6-d0ef02e65d82.png">

убери их, пожалуйста, добавив HTML-тэг `<style>ul{list-style: none;}</style>` в `project/public/index.html` 🙏

2022-02-27 12:28 UTC, yurylavrukhin commented on project/src/components/place-card/place-card.tsx
> +  setActiveCard: any
если пробрасываешь функцию — опиши её тип

давай постараемся сделать проект без `any` 💪 

конкретно в этом случае я думаю мы можем повесить обработчик onMouseEnter на элемент списка `<li>` выше, внутри которого рендерится этот компонент

2022-02-27 12:28 UTC, yurylavrukhin commented on project/src/components/property/property.tsx
> +                  <span>Premium</span>
isFavorite = Premium 🤔

2022-02-27 12:28 UTC, yurylavrukhin commented on project/src/components/rating-stars/rating-stars.tsx
> +  component: string
отличная задумка — создать этот компонент!
давай назовём этот проп componentClassName

2022-02-27 12:28 UTC, yurylavrukhin commented on project/src/mocks/reviews.ts
> +export const REVIEWS = [
я вижу что нигде эти данные не используются 

мы их не хотим нарисовать здесь? 👇 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26966797/155882216-49fe35b9-6897-492c-aed0-1b342b609719.png">

2022-02-27 13:59 UTC, Kiriuha-lucky commented on project/src/components/offers-list/offers-list.tsx
> +        return <li key={id}>{activeCard}<PlaceCard {...offer} setActiveCard={cardEnterHandle} /></li>;
если ее не применить падает ошибка, что не используется, поэтому я пока ее сюда запихнул, а то с этой ошибкой не собирается

2022-03-01 06:47 UTC, yurylavrukhin requested changes
очень красиво получилось! 💙

2022-03-01 06:47 UTC, yurylavrukhin commented on project/src/components/review-form/review-form.tsx
> +          value={rating}
я попросил тебя сделать этот компонент controlled плохо подумав и сломал тебе звёздочки, прости, меня, пожалуйста (сейчас в localState всегда 0)
в этом рейтинге нам не нужен controlled компонент

давай вернём defaultValue как здесь 🙏  https://github.com/htmlacademy-react/838151-six-cities-9/pull/6/commits/29d7794a087ff4b48d6b7e3f3e0eceb01bfe2f6d#diff-3bc457c103c09dde8083adb3bc216d239d197c73f242eca383340f27c5dd5ced

2022-03-01 06:47 UTC, yurylavrukhin commented on project/src/components/review/review.tsx
> +          {DATE.toLocaleString('EN', { month: 'long' })} {DATE.getFullYear()}
😍

2022-03-01 15:29 UTC, merged