feat: add map and neighbors offers to property page
htmlacademy-react/838151-six-cities-9 pull request #8
Opened 2022-03-05 08:39 UTC by Kiriuha-lucky

2022-03-06 04:12 UTC, yurylavrukhin requested changes
компоненты — 🔥 

пофикси все эти ворнинги гитхаба в ПРе, пожалуйста 
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/26966797/156908869-a061ee1b-3801-4609-a621-689b44e79705.png">

2022-03-06 04:12 UTC, yurylavrukhin commented on project/src/components/place-card/place-card.tsx
> +  componentClassName?: string
давай назовём проп `className` и укажем тип литералом строки
```suggestion
  className?: 'near-places' | 'something else'
```

2022-03-06 09:22 UTC, Kiriuha-lucky commented on project/src/components/map/map.tsx
> +export function Map({ offers, componentClassName, selectedOfferId }: MapProps): JSX.Element {
не понял, имеешь ввиду вместо activeCard?

2022-03-07 03:47 UTC, yurylavrukhin requested changes
я заметил что `project/src/components/place-card/place-card.tsx` и `project/src/components/favorite-place-card/favorite-place-card.tsx` не поддерживают проп `isFavorite`

нужно добавить поддержку, посмотри в разметке как это должно быть, похоже при создании компонентов мы этот проп упустили 😱 

остальное выглядит прекрасно! 👍

2022-03-07 03:47 UTC, yurylavrukhin commented on project/src/components/offers-list/offers-list.tsx
> +  className?: ''| 'near-places',
хм, а для какого случая пустая строка?

2022-03-07 03:47 UTC, yurylavrukhin commented on project/src/components/place-card/place-card.tsx
> +  className?: 'near-places' | ''
хм, а для какого случая пустая строка?

кажется она не нужна и её нужно удалить

2022-03-07 03:47 UTC, yurylavrukhin commented on project/src/components/property/property.tsx
> +  const neighborsOffers: Offer[] = offers.filter((offer) => currentOffer?.city.name === offer.city.name).slice(0, 3);
великолепно 🤩

2022-03-08 11:08 UTC, yurylavrukhin requested changes

2022-03-08 11:08 UTC, yurylavrukhin commented on project/src/components/property/property.tsx
> +                <button className={`place-card__bookmark-button ${bookmarkClassName} button`} type="button">
интересно почему класснейм стал другой 🤔 
в разметке `property__bookmark-button button`

2022-03-10 02:56 UTC, merged